package com.msx.springexcel.model;

public enum OverrideProfileHeader {

    RECORD_ID ("Record_ID"),
    OVERRIDE_FLG ("Override (C, S, V)"),
    PRICING_CTRY_CD_SIM ("Pricing Country_sim"),
    PRODUCT_LINE_CD_SIM ("Product Line_sim"),
    PRODUCT_CLUSTER_CD_SIM (""),
    NW_PRODUCT_CD_SIM ("Network Product_sim"),
    LCL_PRODUCT_CD_SIM ("Local Product_sim"),
    ORIG_REGION_CD_SIM ("Origin Region_sim"),
    ORIG_CTRY_CD_SIM ("Origin Country_sim"),
    ORIG_SVC_AREA_CD_SIM ("Origin Service Area_sim"),
    ORIG_ZIP_CD_SIM ("Origin ZIP_sim"),
    DEST_REGION_CD_SIM ("Destination Region_sim"),
    DEST_CTRY_CD_SIM ("Destination Country_sim"),
    DEST_SVC_AREA_CD_SIM ("Destination Service Area_sim"),
    DEST_ZIP_CD_SIM ("Destination ZIP_sim"),
    DOM_INT_CD_SIM ("DOM / INT_sim"),
    SHIP_DT_SIM ("ship_dt_sim"),
    SHIP_CNT_SIM ("Shipments_sim"),
    SHIP_WGHT_KG_SIM ("Shipment weight_KG_sim"),
    SHIP_WGHT_LB_SIM ("Shipment weight_LB_sim"),
    PIECES_CNT_SIM ("Pieces_sim"),
    BILL_TYPE_CD_SIM (""),
    SPOT_RT_FLG_SIM (""),
    CONGESTED_SECTOR_SIM (""),
    KEY_ACCT_SUPPORT_FLG_SIM ("Key Account Support_sim"),
    PIECE_TYPE_CD_SIM ("Piece Type_sim"),
    PU_OPERATOR_TYPE_CD_SIM ("PU_Operator Type_sim"),
    DL_OPERATOR_TYPE_CD_SIM ("DL_Operator Type_sim"),
    PU_VEHICLE_TYPE_CD_SIM ("PU_Vehicle Type_sim"),
    DL_VEHICLE_TYPE_CD_SIM ("DL_Vehicle Type_sim"),
    PU_DENSITY_BAND_CD_SIM ("PU_Density Band_sim"),
    DL_DENSITY_BAND_CD_SIM ("DL_Density Band_sim"),
    PU_STOP_SIM ("PU_Stops_sim"),
    DL_STOP_SIM ("DL_Stops_sim"),
    CLRNCE_TYPE_CD_SIM ("Clearance Type_sim"),
    DATA_ENTRY_TYPE_CD_SIM ("Data Entry Type_sim"),
    DCLBL_TYPE_CD_SIM ("Declarable Type_sim"),
    DIRECT_COST_SIM ("Direct Cost_sim"),
    INDIRECT_COST_SIM ("Indirect Cost_sim"),
    TOTAL_COST_SIM ("Total Cost_sim"),
    GP2_SIM ("GP2_sim"),
    PICKUP_SIM ("Pick up_sim"),
    DELIVERY_SIM ("Delivery_sim"),
    THA1200_OB_SIM ("THA1200_OB_sim"),
    THA1200_IB_SIM ("THA1200_IB_sim"),
    THA1200_ENTRY_SIM ("THA1200_Data_Entry_sim"),
    TERMINAL_HANDLING_SIM ("Terminal Handling_sim"),
    GTW1500_OB_SIM ("GTW1500_OB_sim"),
    GTW1500_IB_SIM ("GTW1500_IB_sim"),
    GATEWAY_SIM ("Gateway_sim"),
    DLH1390_OB_SIM ("DLH1390_OB_sim"),
    DLH1300_ILH1400_SIM ("DLH1300_AND_ILH1400_sim"),
    DLH1390_IB_SIM ("DLH1390_IB_sim"),
    LINEHAUL_SIM ("Linehaul_sim"),
    HUB_SIM ("Hub_sim"),
    CMS1700_OB_SIM ("CMS1700_OB_sim"),
    CMS1700_IB_SIM ("CMS1700_IB_sim"),
    CUSTOMS_SIM ("Customs_sim"),
    CSC2100_BOOKING_SIM ("CSC2100_Booking_sim"),
    CSC2100_CLAIMS_SIM ("CSC2100_Claims_sim"),
    CSC2190_OTHER_SIM ("CSC2190_Other_sim"),
    CSC2100_ECOM_SIM ("CSC2100_Ecom_sim"),
    CSC2100_KAS_SIM ("CSC2100_KAS_sim"),
    CUSTOMER_SERVICE_SIM ("Customer Service_sim"),
    CSA2300_CREDCONTROL_SIM ("CSA2300_CredControl_sim"),
    CSA2300_BILLING_SIM ("CSA2300_Billing_sim"),
    CSA2390_ADMIN_SIM ("CSA2390_Admin_sim"),
    CUSTOMER_ACCOUNTING_SIM ("Customer Accounting_sim"),
    ODI1800_OB_SIM ("ODI1800_OB_sim"),
    ODI1800_IB_SIM ("ODI1800_IB_sim"),
    OTHER_DIRECT_SIM ("Other Direct_sim"),
    EXTRA_BASKET_1_SIM ("Extra Basket_1_sim"),
    EXTRA_BASKET_2_SIM ("Extra Basket_2_sim"),
    EXTRA_BASKET_3_SIM ("Extra Basket_3_sim"),
    EXTRA_BASKET_4_SIM ("Extra Basket_4_sim"),
    EXTRA_BASKET_5_SIM ("Extra Basket_5_sim"),
    EXTRA_BASKET_TYPE_1_SIM ("Extra Basket_Type_1_sim"),
    EXTRA_BASKET_TYPE_2_SIM ("Extra Basket_Type_2_sim"),
    EXTRA_BASKET_TYPE_3_SIM ("Extra Basket_Type_3_sim"),
    EXTRA_BASKET_TYPE_4_SIM ("Extra Basket_Type_4_sim"),
    EXTRA_BASKET_TYPE_5_SIM ("Extra Basket_Type_5_sim");

    private String value;

    OverrideProfileHeader(String value){
        this.value = value;
    }

    public String getValue(){
        return value;
    }

}
