package com.msx.springexcel.model;

public enum OverrideProfileHeader {

    RECORD_ID ("Record_ID"),
    OVERRIDE_FLG ("Override (C, S, V)"),
    PRICING_CTRY_CD_SIM ("Pricing Country_sim"),
    PRODUCT_LINE_CD_SIM ("Product Line_sim"),
    PRODUCT_CLUSTER_CD_SIM (""),
    NW_PRODUCT_CD_SIM ("Network Product_sim"),
    LCL_PRODUCT_CD_SIM ("Local Product_sim"),
    ORIG_REGION_CD_SIM ("Origin Region_sim"),
    ORIG_CTRY_CD_SIM ("Origin Country_sim"),
    ORIG_SVC_AREA_CD_SIM ("Origin Service Area_sim"),
    ORIG_ZIP_CD_SIM ("Origin ZIP_sim"),
    DEST_REGION_CD_SIM ("Destination Region_sim"),
    DEST_CTRY_CD_SIM ("Destination Country_sim"),
    DEST_SVC_AREA_CD_SIM ("Destination Service Area_sim"),
    DEST_ZIP_CD_SIM ("Destination ZIP_sim"),
    DOM_INT_CD_SIM ("DOM / INT_sim"),
    SHIP_DT_SIM ("ship_dt_sim"),
    SHIP_CNT_SIM ("Shipments_sim"),
    SHIP_WGHT_KG_SIM ("Shipment weight_KG_sim"),
    SHIP_WGHT_LB_SIM ("Shipment weight_LB_sim"),
    PIECES_CNT_SIM ("Pieces_sim"),
    BILL_TYPE_CD_SIM (""),
    SPOT_RT_FLG_SIM (""),
    CONGESTED_SECTOR_SIM (""),
    KEY_ACCT_SUPPORT_FLG_SIM ("Key Account Support_sim"),
    PIECE_TYPE_CD_SIM ("Piece Type_sim"),
    PU_OPERATOR_TYPE_CD_SIM ("PU_Operator Type_sim"),
    DL_OPERATOR_TYPE_CD_SIM ("DL_Operator Type_sim"),
    PU_VEHICLE_TYPE_CD_SIM ("PU_Vehicle Type_sim"),
    DL_VEHICLE_TYPE_CD_SIM ("DL_Vehicle Type_sim"),
    PU_DENSITY_BAND_CD_SIM ("PU_Density Band_sim"),
    DL_DENSITY_BAND_CD_SIM ("DL_Density Band_sim"),
    PU_STOP_SIM ("PU_Stops_sim"),
    DL_STOP_SIM ("DL_Stops_sim"),
    CLRNCE_TYPE_CD_SIM ("Clearance Type_sim"),
    DATA_ENTRY_TYPE_CD_SIM ("Data Entry Type_sim"),
    DCLBL_TYPE_CD_SIM ("Declarable Type_sim"),
    DIRECT_COST_SIM (""),
    INDIRECT_COST_SIM (""),
    TOTAL_COST_SIM (""),
    GP2_SIM (""),
    PICKUP_SIM (""),
    DELIVERY_SIM (""),
    THA1200_OB_SIM (""),
    THA1200_IB_SIM (""),
    THA1200_ENTRY_SIM (""),
    TERMINAL_HANDLING_SIM (""),
    GTW1500_OB_SIM (""),
    GTW1500_IB_SIM (""),
    GATEWAY_SIM (""),
    DLH1390_OB_SIM (""),
    DLH1300_ILH1400_SIM (""),
    DLH1390_IB_SIM (""),
    LINEHAUL_SIM (""),
    HUB_SIM (""),
    CMS1700_OB_SIM (""),
    CMS1700_IB_SIM (""),
    CUSTOMS_SIM (""),
    CSC2100_BOOKING_SIM (""),
    CSC2100_CLAIMS_SIM (""),
    CSC2190_OTHER_SIM (""),
    CSC2100_ECOM_SIM (""),
    CSC2100_KAS_SIM (""),
    CUSTOMER_SERVICE_SIM (""),
    CSA2300_CREDCONTROL_SIM (""),
    CSA2300_BILLING_SIM (""),
    CSA2390_ADMIN_SIM (""),
    CUSTOMER_ACCOUNTING_SIM (""),
    ODI1800_OB_SIM (""),
    ODI1800_IB_SIM (""),
    OTHER_DIRECT_SIM (""),
    EXTRA_BASKET_1_SIM (""),
    EXTRA_BASKET_2_SIM (""),
    EXTRA_BASKET_3_SIM (""),
    EXTRA_BASKET_4_SIM (""),
    EXTRA_BASKET_5_SIM (""),
    EXTRA_BASKET_TYPE_1_SIM (""),
    EXTRA_BASKET_TYPE_2_SIM (""),
    EXTRA_BASKET_TYPE_3_SIM (""),
    EXTRA_BASKET_TYPE_4_SIM (""),
    EXTRA_BASKET_TYPE_5_SIM ("");

    private String value;

    OverrideProfileHeader(String value){
        this.value = value;
    }

    public String getValue(){
        return value;
    }

}
